#!/bin/python
# -*- coding: utf-8 -*-
from __future__ import print_function

import requests
import sys
from lxml import html


def focal():
    """(file, string) ->  NoneType
    updates mail signature against an online Word Of the Day Feed.
    """

    #Handle no internet error case to draw focal from log file.
    #Try:
    #    page = requests.get('http://www.focloir.ie/corpus/')
    #Except:
    #    requests.exceptions.ConnectionError
    page = requests.get('http://www.focloir.ie/corpus/')
    tree = html.fromstring(page.text)
    
    eng = tree.xpath('//div[@class="wotdEntryHdr"]/a/span[@class="hwd"]/orth/text()')[0]
    pos = tree.xpath('//span[@class="pos"]/text()')[0]
    gae = tree.xpath('//span[@class="trans"]/text()')[0]
    link= tree.xpath('/html/body/div[3]/div/div[2]/div[2]/div[2]/div[2]/div/div[1]/a/@href')[0]
    
    sig = """
    Irish word of the day:\n
    {2}\n
    {1}; {0}\n
    \n\n {3}
    """.format(pos,eng[0].upper()+eng[1:]," "+"\n       ".join(gae.encode('utf-8').split(',')),link)

    print(sig)

if __name__ == '__main__':
    focal()

sys.exit(0)

